### PR TITLE
Bump versions of everything and refactor where was nececery

### PR DESCRIPTION
**Pull request by kjpopov**
What I've done so far
Everything is latest and greatest
Switch to npm
Change graphql endpoint since the old one was not working (some SSL wired error was throwing when I migrated to HttpLink)
Removed gql modules (was not able to make them work and simplified them) feel free to bring them back to life

What still missing is:
When you are in Server Side Rendering mode (npm run build && npm start) the isomorphic fetch does not work as expected and I have no idea why?! Whenever you click on a person it does a new request to the server. It will be great if you can help me solving that issue.

Thanks!

### CODE REVIEW

**Comment by EddiG** [comment]
Thank you for your efforts!
Honestly, I was expecting that you just update dependencies. I see that you have added additional dependencies to the transpiling process, bumped the minimal required Node.js version and changed the example app. It's maybe good in general but it makes harder to review the PR because I don't know for which reason you did these. That's why I have to ask you to split the PR to the distinct PRs that are aimed to solve the distinct issues.
As a first PR would be great to see the updated dependencies of the main parts like React and Apollo client. If it requires to update the transpiler pipeline it's ok, but please don't do any optimizations on that step, it's another issue.

**Comment by kjpopov** [comment]
Hello and Happy New Year,
I was looking into your proposal to split thinks up, but I did not found a way to split it on a working pull requests, smaller than that one, once you start bumping versions (I started from React Scripts) than things start to break. The reason for every change (except the css and disabling the gql folder/component) was basically broken api-s between older version and new version. Maybe you can comment on the pull request for things that you don't understand and I can try to explain.
Also I did not manage to make the gql folder/component to work and will require your assistance for that if we want to keep that in the project (in my pull request I just do it directly from Person.js)

**Comment by EddiG** [comment]
🎄Happy New Year 🎄
I've created another PR #5 in which I've upgraded packages with a minimal change in dependencies. It works as before, so I hope it will be a good starting point for further improvements and your own customizations. Please, try it on your side and confirm that it works well for you too.

BTW did you consider another solutions like [react-static](https://github.com/nozzle/react-static), [next.js](https://github.com/zeit/next.js/) or [gatsby](https://www.gatsbyjs.org/)? They are more mature than that project. On the other hand if you want to have your own solution with a minimal code, it's a good place to start.

**Comment by EddiG** [comment]
Thanks for your attention to this project! I close this PR in favor of merged #5

**Pull request closed without merging**
